### ISSUE TITLE
Change controller from command line

### ISSUE THREAD

**Issue by dfbarrero** [ISG-UAH/r2p2#13]
Something like:

python r2p2.py --scenario scenario-foo.json --controller controller-foo.json

**Comment by pedrosanchezr** [comment]
Merged ConfigManager class in develop.
This will get the logic for loading the config out from utils.py taking the following responsibilities:
- Load the scenario config
- If a controller path comes by command line argument:
    - Load the controller config from the command line
- If not
    - Load the controller/controllers config from scenario file
- Override (adding some warnings in the console) any parameter from the controller that is also specified in the scenario
    - This allows to change goals, grid_size or any other controller parameter just creating a scenario with this variable overridden. (if we find that some parameter will exist in both files with different purposes, we can add a parameter inside scenario for controller_config, so the ones for the controller are nested)


With this change, I think we are covering the enhancement mentioned in this issue.

I leave it pending on the PR to move develop to master

**Comment by dfbarrero** [comment]
Thanks!
