### ISSUE TITLE
Add abc to requirements.txt

### ISSUE THREAD

**Issue by dfbarrero** [ISG-UAH/r2p2#22]

**Comment by pedrosanchezr** [comment]
I'm not sure to understand this issue.
It seems that abc (Abstract Base Classes) is included by default with Python 3, there is no pypi package for it.
Unless we meant something else, it should work without adding to requirements.

Test:
(run "pip list" on my conda environment):
![image](https://user-images.githubusercontent.com/63917305/96372703-685b0a80-1168-11eb-8585-75cda11b6042.png)

It shows I have no "abc" package.
If I open a python console and import "abc", it works:
![image](https://user-images.githubusercontent.com/63917305/96372738-9b9d9980-1168-11eb-87d0-407dc9e79306.png)

Are we having any exception related to ABC?

**Comment by pedrosanchezr** [comment]
@dfbarrero 
Can you explain what is pending on this?
