### ISSUE TITLE
Avoid dependence of scipy version

### ISSUE THREAD

**Issue by dfbarrero** [ISG-UAH/r2p2#23]
Traceback (most recent call last):

  File "r2p2.py", line 32, in <module>

    import utils as u

  File "/Users/mariadr-moreno/Documents/Malola/Documents/Asignaturas/cursos/Git/R2P2/r2p2/utils.py", line 38, in <module>

    from scipy.misc import imshow

ImportError: cannot import name 'imshow' from 'scipy.misc' (/opt/anaconda3/lib/python3.7/site-packages/scipy/misc/__init__.py)

**Comment by pedrosanchezr** [comment]
As this wasn't allowing any work with R2P2 (at least in my case), I have created a PR to use this module directly from matpotlib. In any case I'll keep working on removing the dependency of scipy once started with that part.

PR #24

**Comment by pedrosanchezr** [comment]
Fixed with PR #25 and removed the fixed version of scipy in PR #28 so it has better compatibility with Python 3.8 or later
